name: e2e
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 9 * * 1'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -f "e2e.Dockerfile" -t lintier-e2e:latest "."
    - name: Run e2e tests
      run: docker run --rm -i lintier-e2e:latest
